### ISSUE TITLE
Add new ScheduledJob state: TimedOut

### ISSUE THREAD

**Issue by abumq** [amrayn/planner#6]
When job is running for more than an specified duration we need to mark it as timed out so that it may be repicked.

A sample log from such an issue is 

```
[2016-10-03 22:00:01]  Executing [CacheHousekeeper]
[2016-10-03 22:01:14]  Files: 0, Responses: 0, Queries: 7, Short Term: 0
[2016-10-03 22:01:14]  Failed [CacheHousekeeper] - PDOStatement::execute(): send of 68 bytes failed with errno=32 Broken pipe in <core_root>/database/DB.php on line 38
[2016-10-03 22:01:14]  Job died [CacheHousekeeper] - Uncaught exception 'ErrorException' with message 'PDOStatement::execute(): send of 68 bytes failed with errno=32 Broken pipe in <core_root>/database/DB.php on line 38' in <core_root>/jobs/ScheduledJobBase.php:35
Stack trace:
#0 [internal function]: ScheduledJobBase->handleError(8, 'PDOStatement::e...', '/home/muflihun/...', 38, Array)
#1 <core_root>/database/DB.php(38): PDOStatement->execute(Array)
#2 <core_root>/queries/Queries.php(146): DB->query('SELECT * FROM S...', Array)
#3 <core_root>/queries/Queries.php(248): Queries::queryBySql('SELECT * FROM S...', Array)
#4 <core_root>/queries/Queries.php(215): Queries::queryByFields(Array, true)
#5 <core_root>/queries/Queries.php(28): Queries::queryById('2', false)
#6 <core_root>/jobs/ScheduledJobBase.php(70): Queries::persist(Object(ScheduledJob))
#7 <core_root>/jobs/CacheHousekeeper.ph in <core_root>/jobs/ScheduledJobBase.php on line 35
Failed to connect to the server (Err: 2/QUERY)
Failed to connect to the server (Err: 2/QUERY)
Fatal error: Uncaught exception 'ErrorException' with message 'PDOStatement::execute(): send of 68 bytes failed with errno=32 Broken pipe in <core_root>/database/DB.php on line 38' in <core_root>/jobs/ScheduledJobBase.php:35
Stack trace:
#0 [internal function]: ScheduledJobBase->handleError(8, 'PDOStatement::e...', '/...', 38, Array)
#1 <core_root>/database/DB.php(38): PDOStatement->execute(Array)
#2 <core_root>/queries/Queries.php(146): DB->query('SELECT * FROM S...', Array)
#3 <core_root>/queries/Queries.php(248): Queries::queryBySql('SELECT * FROM S...', Array)
#4 <core_root>/queries/Queries.php(215): Queries::queryByFields(Array, true)
#5 <core_root>/queries/Queries.php(28): Queries::queryById('2', false)
#6 <core_root>/jobs/ScheduledJobBase.php(70): Queries::persist(Object(ScheduledJob))
#7 <core_root>/jobs/CacheHousekeeper.ph in <core_root>/jobs/ScheduledJobBase.php on line 35
Failed to connect to the server (Err: 2/QUERY)
Failed to connect to the server (Err: 2/QUERY)
[2016-10-03 22:05:01]  Job already running [CacheHousekeeper]
[2016-10-03 22:10:01]  Job already running [CacheHousekeeper]
[2016-10-03 22:15:01]  Job already running [CacheHousekeeper]
[2016-10-03 22:20:01]  Job already running [CacheHousekeeper]
[2016-10-03 22:25:01]  Job already running [CacheHousekeeper]
```

**Comment by abumq** [comment]
Job added `ScheduledJobHousekeeper` (Schedule: `0 * * * *`)
